import { Product, StockStatus } from '../types';

// NOTE: Product images are placeholders. In a real application,
// these would be uploaded and managed via a CMS or admin dashboard.

export const mockProducts: Product[] = [
  {
    id: 'prod_001',
    name: 'Paracetamol',
    category: 'Pain Relief',
    description: 'Effective for relief of mild to moderate pain including headache, migraine, toothache. A common over-the-counter analgesic.',
    dosage: '500mg',
    packSize: '16 Tablets',
    price: 2500,
    wholesalePrice: 2100,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/e0e7ff/3730a3?text=Paracetamol',
    minOrderQuantity: 10,
  },
  {
    id: 'prod_002',
    name: 'Amoxicillin',
    category: 'Antibiotics',
    description: 'A penicillin antibiotic that fights bacteria. Used to treat many different types of infection caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.',
    dosage: '250mg',
    packSize: '21 Capsules',
    price: 5500,
    wholesalePrice: 4800,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/dbeafe/1e3a8a?text=Amoxicillin',
    minOrderQuantity: 5,
  },
  {
    id: 'prod_003',
    name: 'Vitamin C',
    category: 'Supplements',
    description: 'An essential vitamin that your body needs for growth, development and repair of all body tissues. It\'s involved in many body functions, including formation of collagen, absorption of iron, the proper functioning of the immune system, wound healing, and the maintenance of cartilage, bones, and teeth.',
    dosage: '1000mg',
    packSize: '30 Effervescent Tablets',
    price: 3200,
    wholesalePrice: 2800,
    stockStatus: StockStatus.LOW_STOCK,
    imageUrl: 'https://placehold.co/400x400/fee2e2/991b1b?text=Vitamin+C',
    minOrderQuantity: 20,
  },
   {
    id: 'prod_004',
    name: 'Ibuprofen',
    category: 'Pain Relief',
    description: 'A nonsteroidal anti-inflammatory drug (NSAID) used for treating pain, fever, and inflammation. This includes painful menstrual periods, migraines, and rheumatoid arthritis.',
    dosage: '200mg',
    packSize: '24 Tablets',
    price: 3000,
    wholesalePrice: 2500,
    stockStatus: StockStatus.OUT_OF_STOCK,
    imageUrl: 'https://placehold.co/400x400/e0e7ff/3730a3?text=Ibuprofen',
    minOrderQuantity: 10,
  },
  {
    id: 'prod_005',
    name: 'Loratadine',
    category: 'Allergy Relief',
    description: 'An antihistamine that treats symptoms such as itching, runny nose, watery eyes, and sneezing from "hay fever" and other allergies.',
    dosage: '10mg',
    packSize: '30 Tablets',
    price: 4500,
    wholesalePrice: 4000,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/d1fae5/065f46?text=Loratadine',
    minOrderQuantity: 10,
  },
  {
    id: 'prod_006',
    name: 'Omeprazole',
    category: 'Digestive Health',
    description: 'A proton pump inhibitor (PPI) used to treat certain stomach and esophagus problems (such as acid reflux, ulcers).',
    dosage: '20mg',
    packSize: '14 Capsules',
    price: 6800,
    wholesalePrice: 6000,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/fefce8/854d0e?text=Omeprazole',
    minOrderQuantity: 5,
  },
  {
    id: 'prod_007',
    name: 'Aspirin',
    category: 'Pain Relief',
    description: 'Used to reduce fever and relieve mild to moderate pain from conditions such as muscle aches, toothaches, common cold, and headaches.',
    dosage: '300mg',
    packSize: '16 Tablets',
    price: 1500,
    wholesalePrice: 1200,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/e0e7ff/3730a3?text=Aspirin',
    minOrderQuantity: 20,
  },
  {
    id: 'prod_008',
    name: 'Metformin',
    category: 'Diabetes',
    description: 'Used with a proper diet and exercise program and possibly with other medications to control high blood sugar. It is used in patients with type 2 diabetes.',
    dosage: '500mg',
    packSize: '28 Tablets',
    price: 7200,
    wholesalePrice: 6500,
    stockStatus: StockStatus.LOW_STOCK,
    imageUrl: 'https://placehold.co/400x400/f3e8ff/5b21b6?text=Metformin',
    minOrderQuantity: 2,
  },
  {
    id: 'prod_009',
    name: 'Salbutamol Inhaler',
    category: 'Respiratory',
    description: 'Used to relieve symptoms of asthma and chronic obstructive pulmonary disease (COPD) such as coughing, wheezing and feeling breathless.',
    dosage: '100mcg',
    packSize: '200 Doses',
    price: 8500,
    wholesalePrice: 7800,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/e0f2fe/0e7490?text=Inhaler',
    minOrderQuantity: 5,
  },
  {
    id: 'prod_010',
    name: 'Cetirizine',
    category: 'Allergy Relief',
    description: 'An antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching.',
    dosage: '10mg',
    packSize: '14 Tablets',
    price: 2800,
    wholesalePrice: 2400,
    stockStatus: StockStatus.IN_STOCK,
    imageUrl: 'https://placehold.co/400x400/d1fae5/065f46?text=Cetirizine',
    minOrderQuantity: 10,
  }
];